### ISSUE TITLE
Investigate Deployment Preview Comments

### ISSUE THREAD

**Issue by GeoffreyXue** [quarcs-lab/quarcs-bolivia#105]
### Current State
The messages that appeared in previous PRs, like #93, no longer appear after the transfer. Investigate and follow up on the issue

**Comment by GeoffreyXue** [comment]
@cmg777 After investigating this issue, I found that aside from the deploy previews, there are actual deploy notifications that correspond to the deploy previews that have to be enabled. These can be found under Site Configurations -> Notifications -> Emails and Webhooks. Do you have all of these notifications enabled on the project?

![image](https://github.com/quarcs-lab/quarcs-bolivia/assets/85135277/75f9f7cf-e7ec-40e0-9dce-b3b529b2a2ec)

**Comment by cmg777** [comment]
Hi @GeoffreyXue 
Only the following notifications are active

<img width="2395" alt="Notifications | Site configuration | quarcs-bolivia | Netlify 2023-10-06 15-36-26" src="https://github.com/quarcs-lab/quarcs-bolivia/assets/26156651/6a76c346-3a8c-4e1e-a39b-2647875c1eb3">

**Comment by GeoffreyXue** [comment]
@cmg777 Interesting, it seems like it's named slightly different, which is a big trange. I think trying out the notification setup that mirrors mine above might fix the problem. If you'd like, I can also go in and modify the notifications myself - up to you!

**Comment by cmg777** [comment]
@GeoffreyXue 
Sure, please go ahead and make the necessary modifications. Feel free to ask if you require any extra credentials.

**Comment by GeoffreyXue** [comment]
@cmg777 Yeah, I believe I will need the credentials for your Netlify site. Do you have a preferred way of sending them? Any method works for me.

**Comment by cmg777** [comment]
@GeoffreyXue 
I will send them by email. What email address would your prefer?

**Comment by GeoffreyXue** [comment]
@cmg777 xuegeoff@gmail.com works!

**Comment by cmg777** [comment]
@GeoffreyXue 
OK, I just sent you an email to that address.

**Comment by GeoffreyXue** [comment]
@cmg777 Unlinking + relinking the project seems to have done the trick, the deploy previews now work after pushing a fresh commit!
Ex: #106

Marking as closed.
